spring:
  config:
    import: "optional:file:.env[.properties]"
  datasource:
    url: jdbc:postgresql://localhost:5432/delivery_db
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true

jwt:
  secret:
    key: ${SECURITY_JWT_SECRET}

server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

logging:
  pattern:
    console: '%clr(%-5level){green} %clr(%logger{36}.%M\(\)){cyan}: %msg%n'

gemini:
  api:
    key: ${GEMINI_API_KEY}

jeogiyo:
  delivery-area:
    road-address-prefix: 서울특별시 종로구
    roads:
      - 세종대로
      - 새문안로
      - 종로1길
      - 종로3길
      - 사직로
      - 삼봉로
      - 자하문로
      - 율곡로
      - 우정국로
      - 경희궁길
      - 경희궁1길